### ISSUE TITLE
Typo in Email methods

### ISSUE THREAD

**Issue by sebasira** [mailersend/mailersend-java#60]
Hi! I'm starting to use this SDK, and I think that there's a typo in the methods of the [Email class](https://github.com/mailersend/mailersend-java/blob/main/src/main/java/com/mailersend/sdk/emails/Email.java#L91)

There's an `addRecipient` method, and there are also `AddRecipient` and `AddRecipients` methods. I think maybe they should be with lowercase.

Also the method to add CC and BCC are with capital uppercase. 

Best regards! Nice work!

**Comment by sebasira** [comment]
I've just notice there's already a [pull-request](https://github.com/mailersend/mailersend-java/pull/34) about this.

**Comment by perezodetteblessie-glitch** [comment]
That's issue is already in pull-request, Thankyou!
